### ISSUE TITLE
Unable to use Following REST API 

### ISSUE THREAD

**Issue by azri** [OfficeDev/PHP-App-for-SharePoint#2]
Hi,

We are trying to use Following REST API calls https://msdn.microsoft.com/EN-US/library/office/dn194080.aspx in the PHP App for Sharepoint. 

Currently we are using Read Permissions. So when we try to run fetch currently logged in user followed information using the API call http://<siteCollection>/<site>/_api/social.following/my/followed(types=15) , the response is "Access Denied, You do not have permission to perform this action or access this resource" 

We added this app in the required sites and we are able to read the  documents in the site. Do we need to add any extra permissions for the app?

**Comment by Ricalo** [comment]
Mmm this may be a problem with the permission scope instead of the right.
In the app manifest, try to change
``
<AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="Read" />
``
to 
``
<AppPermissionRequest Scope="http://sharepoint/social/core" Right="Read" />
``
or
``
<AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="Read" />
``
For more information, check [App permission scopes and available rights for social features in SharePoint Server 2013](https://msdn.microsoft.com/en-us/library/office/jj163864.aspx#bkmk_AppPerms).
Let me know if this helps.

**Comment by azri** [comment]
Thanks for the quick reply.

I would like to use this app to read Site Content like Document, List libraries and for social actions like Following, Site Feed. So can I mention multiple <AppPermissionRequest> in the manifest file. Something like below

<AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="Read" />
 <AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="Read" />

**Comment by Ricalo** [comment]
Yes, in that case you'd have to specify multiple permissions in the manifest.

**Comment by azri** [comment]
Thanks Ricalo. Will check by adding multiple permissions. 

I have a general doubt related Sharepoint Social Feed REST API. We are using Office 365 E3 and for social feed we configured Yammer. Now when we if use Social Feed REST API to add new Post or like, will it be posted on Yammer?

**Comment by Ricalo** [comment]
It should be posted on Yammer, but I recommend posting that question to StackOverflow with the Office 365 tag. You should get a more complete answer there.

**Comment by Ricalo** [comment]
I believe this issue has been resolved, feel free to reopen if that's not the case.

**Comment by azri** [comment]
The issue is resolved.
