### ISSUE TITLE
Is it possible to initiate the authentication from PHP application.

### ISSUE THREAD

**Issue by azri** [OfficeDev/PHP-App-for-SharePoint#4]
The application is able to get the access token only if it is run from sharepoint. Is there a way to fetch the access token, if the application is accessed directly?

**Comment by Ricalo** [comment]
Mmm... you can try the following:
When your user start from the app directly, check if the request has an access token. 
If there's no access token, send them to the appredirect URL.
If they're already signed in to SharePoint, the page will send them back to the application. Otherwise they would have to sign in and then the page would send them back to your application.

You can get the appredirect URL from the Site Contents page of the SharePoint site. Hover over the icon of your app and you will see the appredirect URL.

**Comment by Rick-Kirkham** [comment]
Also, note that SharePoint uses a different OAuth token flow for apps that are launched from outside SharePoint. See https://msdn.microsoft.com/en-us/library/office/jj687470.aspx

**Comment by azri** [comment]
Ricalo,
We are currently using the same approach. I am curious to know other authentication options possible.

**Comment by Ricalo** [comment]
@azri , please check the article that @Rick-Kirkham mentioned. It has better ideas than just sending users to appredirect.
